### ISSUE TITLE
make use of appveyor for windows

### ISSUE THREAD

**Issue by BlackIkeEagle** [Parchive/par2cmdline#91]
check how to use appveyor

**Comment by Safihre** [comment]
Just set this up, it's very simple.
Doesn't run the tests, but builds them for both platforms. Everything works, including OpenMP. 
And funny enough, the file size is back to 440Kb 👍 👍 
Artifacts:
https://ci.appveyor.com/project/Safihre/par2cmdline/build/job/ggytbvx94dg36fns/artifacts
https://ci.appveyor.com/project/Safihre/par2cmdline/build/job/rtomky27y1jyqwc0/artifacts
```yaml
version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform:
- x64
- x86
environment:
  VisualStudioVersion: 10.0
build:
  project: par2cmdline.vcxproj
  verbosity: normal
artifacts:
- path: x64\Release\par2.exe
- path: Win32\Release\par2.exe
```
